---
ENV_NAME: wpts
DEBUG: yes

ansible_python_interpreter: /usr/bin/env python3
ansible_user: ubuntu

samba_user: Administrator
samba_password: Password01@
samba_realm: SAMDOM.EXAMPLE.COM
samba_basedn: DC=samdom,DC=example,DC=com

OS_SERVERS:

  - name: dc0
    image: packer-ubuntu-16.04-x86_64
    userdata: "templates/userdata.sh"
    groups: ['samba-common', 'samba-dc']

  - name: win0
    image: windows-server-2012r2-x86_64-live-snapshot
    userdata: "templates/userdata.ps1"
    flavor: c1.c2r4
    boot_from_volume: yes
    volume_size: 100
    groups: ['windows-common']

primary_dc_name: dc0

# one of the dir name in templates
test_suite_name: Kerberos

windows_protocol_test_suites:
  Kerberos:
    category: Kerberos
    msi: Kerberos-TestSuite-ServerEP.msi
    ptfconfig: Kerberos_ServerTestSuite.deployment.ptfconfig
  ADFamily:
    category: ADFamily
    msi: ADFamily-TestSuite-ServerEP.msi
    ptfconfig: AD_ServerTestSuite.deployment.ptfconfig
  MS-AZOD:
    category: AZOD
    msi: MS-AZOD-TestSuite-ODEP.msi
    ptfconfig: MS-AZOD_ODTestSuite.deployment.ptfconfig


VSCOMN: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7"
VSCOMNTOOLS: "{{VSCOMN}}\\Tools"
VSCOMNIDE: "{{VSCOMN}}\\IDE"
MSTEST: "{{VSCOMNIDE}}\\MSTest.exe"
