---

- name: render {{operation}}.sh script
  template:
    src: templates/{{operation}}.sh
    dest: "{{repo_root}}/bin/{{operation}}.sh"
    mode: 0755

- name: run {{operation}}.sh script
  become: yes
  shell: "{{repo_root}}/bin/{{operation}}.sh"

- name: render supervisor conf for samba
  become: yes
  template:
    src: templates/supervisor-samba.conf
    dest: /etc/supervisor/conf.d/samba.conf

- name: restart supervisor service
  become: yes
  service:
    name: supervisor
    state: restarted

- name: wait for samba to run
  wait_for:
    timeout: 5

- name: check samba status
  become: yes
  command: supervisorctl status samba
  register: samba_status_result

- name: failed if samba not running
  fail:
    msg: "samba is not running"
  when:
    - '"RUNNING" not in samba_status_result.stdout'
