---
# A playbook to set up a samba server as AD DC
# ref: https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller

- name: disable resolvconf
  become: yes
  service:
    name: resolvconf
    enabled: no

- name: kill existing samba service and its friends
  become: yes
  shell: "killall --quiet --wait samba smbd nmdb winbindd || true"

- name: make sure /etc/hosts resolves DC's FQDN and short name to LAN IP
  become: yes
  lineinfile:
    path: "/etc/hosts"
    line: "{{openstack.private_v4}} {{ansible_hostname}}.{{samba_realm}} {{ansible_hostname}}"

- name: remove existing samba files from previous installation if any
  become: yes
  file:
    path: "{{ ansible_env[item] }}"
    state: absent
  when: item in ansible_env
  with_items:
    - CONFIGFILE
    - LOCKDIR
    - STATEDIR
    - CACHEDIR
    - PRIVATE_DIR

- name: remove an existing /etc/krb5.conf file
  become: yes
  file:
    path: "/etc/krb5.conf"
    state: absent

- name: include tasks/mit-krb5.yml if enabled
  include_tasks: tasks/mit-krb5.yml
  when: mit_krb5_enabled is defined and mit_krb5_enabled

- name: make install samba
  become: yes
  command: "make install"
  args:
    chdir: "{{ repo_root }}"

- name: Create a link to krb5.conf
  become: yes
  file:
    src: /usr/local/samba/private/krb5.conf
    dest: /etc/krb5.conf
    force: true
    state: link
    owner: root
    group: root

- name: set fact for primary_dc_id
  set_fact:
    primary_dc_id: "{{groups[primary_dc_name][0]}}"
  tags:
    - always

- name: set fact for primary_dc_ip
  set_fact:
    primary_dc_ip: "{{hostvars[primary_dc_id].openstack.private_v4}}"
  tags:
    - always

- name: render /etc/resolv.conf
  become: yes
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver {{primary_dc_ip}}
      search {{samba_realm}}
  tags:
    - render-resolv-conf

- name: include tasks/supervisor.yml
  include_tasks: tasks/supervisor.yml

- name: provision primary DC
  become: yes
  command: >
    /usr/local/samba/bin/samba-tool domain provision --use-rfc2307
    --realm={{samba_realm}}
    --domain={{samba_domain}}
    --server-role=dc
    --adminpass='{{samba_password}}'
    --krbtgtpass='{{samba_password}}'
    --machinepass='{{samba_password}}'
    --dnspass='{{samba_password}}'
    --option='dns forwarder={{samba_dns_forwarder}}'
    --option='kccsrv:samba_kcc={{use_samba_kcc}}'
    --option='ldapserverrequirestrongauth=no'
  when:
    - '"samba-dc" in group_names'
    - 'primary_dc_name in group_names'
  tags:
    - samba-dc-privison
  register: domain_provison_task

- name: join backup DCs to domain
  become: yes
  command: >
    /usr/local/samba/bin/samba-tool domain join {{samba_domain}} DC
    --server={{primary_dc_name}}
    --realm={{samba_realm}}
    --adminpass={{samba_password}}
    --username={{samba_username}}
    --password={{samba_password}}
  when:
    - '"samba-dc" in group_names'
    - 'primary_dc_name not in group_names'
  tags:
    - samba-dc-join
  register: domain_join_task

- name: copy samba back file to remote dc
  copy:
    src: "{{samba_backup_file}}"
    dest: "{{ansible_env.HOME}}/{{samba_backup_file}}"
  when:
    - samba_backup_file is defined

- name: make sure samba restore target dir exists
  file:
    state: directory
    path: "{{samba_restore_target_dir}}"
  when:
    - samba_restore_target_dir is defined

- name: restore db from backup
  command: >
    /usr/local/samba/bin/samba-tool domain backup restore
    --newservername={{primary_dc_name}}
    --backup-file={{samba_backup_file}}
    --targetdir={{samba_restore_target_dir}}
    --username={{samba_username}}
    --password={{samba_password}}
  when:
    - '"samba-dc" in group_names'
    - 'primary_dc_name in group_names'
    - 'samba_backup_file is defined'
    - 'samba_restore_target_dir is defined'
