---

- name: check samba binary
  stat:
    path: /usr/local/samba/sbin/samba
  register: stat_result

- name: install samba if not exist
  include_tasks: install.yml
  when:
    - not stat_result.stat.exists
