#cloud-config

# Install Samba AD DC on first boot

packages:
 - screen
 - git
 - build-essential
 - libacl1-dev
 - libattr1-dev
 - libblkid-dev
 - libgnutls-dev
 - libreadline-dev
 - python-dev
 - libpam0g-dev
 - python-dnspython
 - gdb
 - pkg-config
 - libpopt-dev
 - libldap2-dev
 - dnsutils
 - libbsd-dev
 - attr
 - krb5-user
 - docbook-xsl
 - libcups2-dev
 - acl
 - bison
 - debhelper
 - docbook-xml
 - docbook-xsl
 - flex
 - libaio-dev
 - libbsd-dev
 - libcap-dev
 - libcups2-dev
 - libncurses5-dev
 - libpam0g-dev
 - libpopt-dev
 - libreadline-dev
 - perl
 - perl-modules
 - libparse-yapp-perl
 - pkg-config
 - python-all-dev
 - python-dnspython
 - xsltproc
 - zlib1g-dev
 - autoconf
 
package_upgrade: true

runcmd:
 - set -x
 - |
    cat >  /usr/local/bin/clone-samba << EOF
    #!/bin/bash
    set -x
    set -e
    cd ~
    git clone git://git.catalyst.net.nz/samba.git
    cd samba
    git remote add catalyst git://git.catalyst.net.nz/samba.git
    git remote add abartlet git://git.samba.org/abartlet/samba.git
    git remote set-url origin git://git.samba.org/samba.git
    git fetch catalyst
    mkdir -p ~/autobuild
    EOF
 - chmod 0755 /usr/local/bin/clone-samba
 - |
    cat >  /usr/local/bin/build-samba << EOF
    #!/bin/bash
    set -x
    set -e
    cd ~
    cd samba
    git fetch catalyst
    git checkout catalyst/for-cloud-autobuild
    AUTOBUILD_CLEAN_TREE_OVERRIDE=1 ./script/autobuild.py --nocleanup --testbase=/home/ubuntu/autobuild --tail
    EOF
 - chmod 0755 /usr/local/bin/build-samba
 - [ su, ubuntu, -l, -c, /usr/local/bin/clone-samba]
 - [ su, ubuntu, -l, -c, /usr/local/bin/build-samba]


