---
# tasks file for netinf-manager

# If you have sourced an OpenStack RC file, connecting to the Catalyst
# Cloud is as simple as running the os_auth module with no additional
# parameters.
- name: Connect to the Catalyst Cloud
  os_auth:

# OpenStack won't allow to delete networks if there are ports attached to them
# so deleting the router first if set_state=absent, later we the same task is
# is included again when set_state == 'present'
- import_tasks: tasks/routers.yml
  when: set_state == 'absent'
  tags:
    - routers

- import_tasks: tasks/networks.yml
  tags:
    - networks

- import_tasks: tasks/subnets.yml
  when: set_state == 'present'
  tags:
    - subnets

- import_tasks: tasks/routers.yml
  when: set_state == 'present'
  tags:
    - routers

- import_tasks: tasks/security-groups.yml
  tags:
    - security-groups

- import_tasks: tasks/security-group-rules.yml
  when: set_state == 'present'
  tags:
    - security-group-rules
