---
# tasks file for master-manager

# If you have sourced an OpenStack RC file, connecting to the Catalyst
# Cloud is as simple as running the os_auth module with no additional
# parameters.
- name: Connect to the Catalyst Cloud
  os_auth:
  tags:
    - master

- name: Disassociate a floating IP from master
  os_floating_ip:
    state: 'absent'
    purge: true
    server: "{{ env_prefix }}-{{ site_basename }}1-{{ node_basename }}1"
    wait: true
  ignore_errors: true
  when: set_state == 'absent'
  tags:
    - master
    - floating_ip

  # Create  Instance
- name: Manage master compute instance
  os_server:
    state: "{{ set_state | default('present') }}"
    name: "{{ env_prefix }}-{{ site_basename }}1-{{ node_basename }}1"
    key_name: "{{ keypair_name }}"
    flavor: "{{ master_flavour }}"
    nics:
      - net-name: "{{ env_prefix }}-network1"
    auto_ip: false
    image: "{{ master_image }}"
    security_groups: "{{ master_security_group }}"
    meta: "group=master_group,{{ env_prefix }}=env_master,groups={{ env_prefix }}_master"
    user_data: |
      #cloud-config
      hostname: "{{ env_prefix }}-{{ site_basename }}1-{{ node_basename }}1"
      fqdn: "{{ env_prefix }}-{{ site_basename }}1-{{ node_basename }}1.{{ domain }}"
      manage_etc_hosts: false
      packages:
        - python-minimal
        - language-pack-en
  tags:
    - master

- name: Assign a floating IP to master
  os_floating_ip:
    state: 'present'
    server: "{{ env_prefix }}-{{ site_basename }}1-{{ node_basename }}1"
    wait: true
  when: set_state == 'present'
  register: master_floating_ip_info
  tags:
    - master
    - floating_ip

- name: Output floating IP
  debug:
    var: master_floating_ip_info.floating_ip.floating_ip_address
  when: set_state == 'present' and master_floating_ip_info.floating_ip.floating_ip_address is defined
  tags:
    - master
    - floating_ip
