---

- name: which packer
  shell: which packer
  ignore_errors: yes
  register: which_packer_result

- name: download packer if not exist
  get_url:
    url: https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
    dest: /tmp/packer_1.2.5_linux_amd64.zip
    checksum: "sha256:bc58aa3f3db380b76776e35f69662b49f3cf15cf80420fc81a15ce971430824c"
  when:
    - which_packer_result.failed

- name: unarchive packer zip to bin path
  become: yes
  unarchive:
    src: /tmp/packer_1.2.5_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0555
    remote_src: yes
  when:
    - which_packer_result.failed

- name: load samba dependencies package list
  include_vars: "{{package_list_file}}"

- name: create temp file for packer template
  tempfile:
    state: file
    prefix: "ansible-packer-"
    suffix: ".json"
  register: tempfile_task

- name: render packer config file
  template:
    src: templates/template.json
    dest: "{{tempfile_task.path}}"
    validate: packer validate %s
  vars:
    apt_install_packages: "{{packages|join(' ')}}"

- name: packer build
  command: packer build "{{tempfile_task.path}}"
