---
- name: render /etc/resolv.conf
  become: yes
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver {{ runner_nameserver }}
      search {{ samba_realm }}
  tags: resolv

- name: copy model file to runner and make readonly
  copy:
    src: "files/{{model_file_name}}"
    dest: "{{ansible_env.HOME}}/samba/{{model_file_name}}"
    mode: 0444
  tags: model

- name: render templates
  template:
    src: templates/{{item}}
    dest: "{{repo_root}}/{{item}}"
    mode: 0755
  with_items:
    - run.py
  tags: templates

- name: trigger run.py
  command: python run.py --all
  args:
    chdir: "{{repo_root}}"
  tags: run

- name: set fact for finished_at
  set_fact:
    finished_at: "{{ansible_date_time.iso8601_basic_short}}"
  tags:
    - send-email

- name: set fact based on finished_at
  set_fact:
    summary_path: "{{repo_root}}/{{stats_dir_name}}/summary.txt"
    summary_dest: "{{stats_tar_dest}}/{{finished_at}}-summary.txt"
    tar_path: "{{repo_root}}/{{stats_dir_name}}.tgz"
    tar_dest: "{{stats_tar_dest}}/{{finished_at}}-{{stats_dir_name}}.tgz"
  tags:
    - send-email

- name: fetch summary.txt
  fetch:
    src: "{{summary_path}}"
    dest: "{{summary_dest}}"
    flat: yes
  tags:
    - fetch-summary-txt
    - send-email

- name: set fact for summary_content
  set_fact:
    summary_content: "{{lookup('file', summary_dest)}}"
  tags:
    - send-email

- name: fetch tar file
  fetch:
    src: "{{tar_path}}"
    dest: "{{tar_dest}}"
    flat: yes
  tags:
    - fetch-stats-tarfile
    - send-email

- name: send email
  mail:
    host: mail.catalyst.net.nz
    port: 465
    username: "{{lookup('env', 'EMAIL_USERNAME')}}"
    password: "{{lookup('env', 'EMAIL_PASSWORD')}}"
    from: "ansible"
    to:
      - "{{email_recipient}}"
    subject: "A new traffic replay for samba performance test finished"
    body: |
      {{summary_content}}
      View or download all data at http://joeg-pc/traffic-replay/
    attach:
      - "{{summary_dest}}"
      - "{{tar_dest}}"
  delegate_to: localhost
  ignore_errors: yes
  tags:
    - send-email
