#!/usr/bin/env ansible-playbook
---

- import_playbook: openstack.yml

- name: use packer role to build windows image
  hosts: localhost
  roles:
    - name: packer
      OS_IMAGE_NAME: windows-server-2012r2-x86_64-live-snapshot
