#!/usr/bin/env ansible-playbook
---

- name: use packer role to build windows image
  hosts: localhost
  roles:

    - name: openstack
      state: present

    - name: packer
      OS_IMAGE_NAME: windows-server-2012r2-x86_64-live-snapshot
      PACKER_OUTPUT_IMAGE_NAME: temporary-windows

    - name: openstack
      state: absent
