---
- hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars.yml
  vars_prompt:
    - name: "docker_registry_username"
      prompt: "What's the username for your docker registry account"
      private: no
    - name: "docker_registry_password"
      prompt: "What's the password for your docker registry account"
      private: yes

  tasks:

    - name: load samba dependencies package list
      include_vars: "../package-lists/ubuntu-1404"

    - name: create temp dir for Dockerfile
      file:
        path: /tmp/samba-docker-image
        state: directory
        mode: 0755

    - name: render Dockerfile with package list
      template:
        src: templates/Dockerfile
        dest: /tmp/samba-docker-image
        force: yes

    - name: remove docker image
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        tag: latest
        state: absent
        force: yes

    - name: login to docker registry to push image later
      docker_login:
        registry: "{{ DOCKER_REGISTRY }}"
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"

    - name: build docker image
      docker_image:
        path: /tmp/samba-docker-image
        name:  "{{ DOCKER_IMAGE }}"
        tag: latest
        state: build
        nocache: yes
        push: yes
        rm: yes
