---
- hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:

    - name: load samba dependencies package list
      include_vars: "../package-lists/ubuntu"

    - name: create temp dir for Dockerfile
      file:
        path: /tmp/samba-docker-image
        state: directory
        mode: 0755

    - name: render Dockerfile with package list
      template:
        src: templates/Dockerfile
        dest: /tmp/samba-docker-image
        force: yes

    - name: pip install common packages
      become: true
      pip:
        name: "{{ item }}"
      with_items:
        - docker-py  # required by docker_image

    - name: remove docker image
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        tag: latest
        state: absent
        force: yes

    - name: build docker image
      docker_image:
        path: /tmp/samba-docker-image
        name:  "{{ DOCKER_IMAGE }}"
        tag: latest
        state: build
        nocache: yes
        push: no
        rm: yes

    - name: print help msg to login to docker registry
      debug:
        msg: "docker login {{ DOCKER_REGISTRY }}"

    - name: print help msg to push to docker registry
      debug:
        msg: "docker push {{ DOCKER_IMAGE }}"
