---
# will be used by openstack role to create network, router, etc
DEBUG: yes

ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/env python3


repo_url: https://gitlab.com/catalyst-samba/samba.git
repo_branch: master
repo_root: "{{ansible_env.HOME}}/samba"


samba_realm: 'SAMDOM.EXAMPLE.COM'
samba_domain: 'SAMDOM'
samba_username: 'Administrator'
samba_password: 'Password01@'

dns_domain_name: "{{samba_realm|lower}}"

ENV_NAME: indeed

num_dcs: 2
num_users: 5000
num_groups: 750
num_groups_per_user: 15
num_users_in_largest_group: 3000

# default vars to create dc in openstack
OS_AUTO_FLOATING_IP: yes
OS_FLAVOR_NAME: c1.c1r1
OS_IMAGE_NAME: ubuntu-16.04-x86_64

PACKER_OUTPUT_IMAGE_NAME: "packer-{{OS_IMAGE_NAME}}"

# must match above image
package_list_file: "{{ playbook_dir }}/../package-lists/ubuntu"

OS_NAMESERVERS: [202.78.247.197, 202.78.247.198, 202.78.247.199]

OS_META_GROUPS:
  - samba-common
  - samba-dc

OS_SERVER_PREFIX: "dc"

run_generate: no
run_replay: no
run_summary: no

primary_dc_name: dc0

OS_SERVERS_MISC:
  - name: tr0
    groups:
      - samba-common
      - samba-traffic-runner

OS_SERVERS_DCS: "{{range(num_dcs)|list}}"

OS_SERVERS: "{{OS_SERVERS_DCS + OS_SERVERS_MISC}}"

run_packer_build: no

  # - name: windows0
    # image: windows-server-2016-x86_64
    # boot_from_volume: yes
    # volume_size: 100
    # userdata: "{{lookup('template', 'templates/userdata.ps1')}}"
    # groups:
      # - domain-computer
      # - ad-ds-dc
    # security_groups:
      # - rdp
      # - winrm
      # - ad-domain-and-clients

  # - name: windows1
    # image: windows-server-2016-x86_64
    # boot_from_volume: yes
    # volume_size: 100
    # groups:
      # - ad-ds-common
      # - ad-ds-dc
    # security_groups:
      # - rdp
      # - winrm
      # - ad-domain-and-clients
