---
- name: win_ping
  win_ping:

- name: win_chocolatey install packages
  win_chocolatey:
    name: "{{item}}"
  loop:
    - firefox
    - wireshark
    - winpcap
    - everything
    - notepadplusplus
    - gow
    - cmder
    - openssh
    - dotnet4.7.1
  tags:
    - chocolatey

- name: win_chocolatey install openssh
  win_chocolatey:
    name: "openssh"
    params: "'/SSHServerFeature'"
  tags:
    - chocolatey

- name: set fact for primary_dc_ip
  set_fact:
    primary_dc_ip: "{{hostvars[primary_dc_name].openstack.private_v4}}"

- name: config the DNS client on Windows network adapters
  win_dns_client:
    adapter_names: "Ethernet"
    ipv4_addresses: ["{{primary_dc_ip}}", 202.78.247.199]

- name: ensure the named domain is reachable
  win_domain:
    dns_domain_name: "{{dns_domain_name}}"
    safe_mode_password: "{{ samba_password }}"
  register: win_domain_task
  when: '"windows-dc" in group_names'
  tags:
    - win_domain

- name: install features for windows-dc
  win_feature:
    name:
      - Net-Framework-Core
      - AD-Domain-Services
    include_sub_features: yes
    include_management_tools: yes
  when: '"windows-dc" in group_names'
  tags:
    - win_feature

- name: reboot host if required
  win_reboot:
  when: win_domain_task.reboot_required

- name: join windows computer to domain
  win_domain_membership:
    dns_domain_name: "{{dns_domain_name}}"
    domain_admin_user: "Administrator@{{ samba_realm }}"
    domain_admin_password: "{{ samba_password }}"
    state: domain
  register: win_domain_membership_task
  when:
    - '"windows-dc" in group_names'
    - 'primary_dc_name not in group_names'
  tags:
    - win_domain_membership

- name: reboot host if required
  win_reboot:
  when:
    - '"windows-dm" in group_names'
    - win_domain_membership_task.reboot_required

- name: promote windows computer as domain controller
  win_domain_controller:
    dns_domain_name: "{{dns_domain_name}}"
    domain_admin_user: "{{ansible_user}}@{{dns_domain_name}}"
    domain_admin_password: "{{ samba_password }}"
    safe_mode_password: "{{ samba_password }}"
    state: domain_controller
    log_path: C:\ansible_win_domain_controller.txt
  register: win_domain_controller_task
  when:
    - '"windows-dc" in group_names'
    - 'primary_dc_name in group_names'
  tags:
    - win_domain_controller

- name: reboot host if required
  win_reboot:
  when: win_domain_controller_task.reboot_required
