#!/usr/bin/python

import os
import sys
import mailbox
import argparse
import re
import requests
import errno
import collections
import time

import config
from email_utils import filter_by_date, count_lines, draw_histogram

SAMBA_STDOUT_CACHE = os.path.join(os.path.dirname(__file__), 'cache/autobuild')
FLAKEY_LOG_CACHE = os.path.join(os.path.dirname(__file__), 'cache/flakey_log')

def get_cvs_email():
    mbox = mailbox.mbox(config.MAILBOX)
    subj_match = re.compile(r'autobuild[\w\[\].-]*: '
                            'intermittent test failure detected').match
    messages = [x for x in mbox if
                subj_match(x.get('Subject'))]

    return messages


def get_cvs_links():
    messages = get_cvs_email()
    urlre = re.compile(r'http://git.samba.org/autobuild.flakey[\w.-]*/'
                       '\d\d\d\d-\d\d-\d\d-\d+/[\w.]+').findall
    links = []
    for m in messages:
        s = m.get_payload()
        links.extend(urlre(s))

    return links


def update_cache(cache, link_end, force=False):
    try:
        os.makedirs(cache)
    except OSError, e:
        if e.errno != errno.EEXIST:
            raise

    for url in get_cvs_links():
        if not url.endswith(link_end):
            continue
        fn = re.sub(r'[^\w.-]+', '+', url[7:])
        ffn = os.path.join(cache, fn)
        if force or not os.path.exists(ffn):
            print >> sys.stderr, "fetching %s" % url
            try:
                r = requests.get(url)
            except requests.ConnectionError as e:
                print >> sys.stderr, "could not fetch '%s': %s" % (url, e)
                continue
            f = open(ffn, 'w')
            f.write(r.text.encode('utf-8'))
            f.close()


def print_all_links():
    for x in get_cvs_links():
        print x


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--print-links', action='store_true',
                        help="print all the autobuild links and exit")

    parser.add_argument('-c', '--count', type=int,
                        help="print this many errors (default all)")

    parser.add_argument('--file-regex', default='samba.stdout$',
                        help="look at files matching this regex")

    parser.add_argument('--line-regex', default='^UNEXPECTED',
                        help="look for lines matching this regex")

    parser.add_argument('--filter-line',
                        help="only look at matched parts of the line")

    parser.add_argument('--since',
                        help=("restrict to filenames containing dates "
                              "> this (YYYY-MM-DD)"))

    parser.add_argument('--histogram', action='store_true',
                        help=("draw a graph of monthly counts"))

    parser.add_argument('--flakey-log', action='store_true',
                        help=("print statistics from flakey.log"))

    args = parser.parse_args()

    if args.print_links:
        print_all_links()
        sys.exit()

    if args.flakey_log:
        update_cache(FLAKEY_LOG_CACHE, 'flakey.log')
        count_lines(fn_re='flakey.log$',
                    line_re=r"\w+: \[\w+\] failed '.+' with status",
                    cache=FLAKEY_LOG_CACHE,
                    count=args.count,
                    since=args.since,
                    filter_re=args.filter_line)
        sys.exit()

    update_cache(SAMBA_STDOUT_CACHE, 'samba.stdout')

    if args.histogram:
        draw_histogram(fn_re=args.file_regex,
                       line_re=args.line_regex,
                       cache=SAMBA_STDOUT_CACHE,
                       since=args.since,
                       filter_re=args.filter_line)
        sys.exit()

    count_lines(fn_re=args.file_regex,
                line_re=args.line_regex,
                cache=SAMBA_STDOUT_CACHE,
                count=args.count,
                since=args.since,
                filter_re=args.filter_line)


main()
