#!/usr/bin/env ansible-playbook
---
- name: apply role samba-common
  hosts: samba-common
  serial: 50
  tasks:
    - name: include role
      include_role:
        name: samba-common
      when:
        - ENV_NAME in group_names
