#!/bin/bash

# winpcap needs click to install, use npcap instead
# wget https://www.winpcap.org/install/bin/WinPcap_4_1_3.exe -O winpcap-nmap.exe

wget https://nmap.org/npcap/dist/npcap-0.96.exe -O npcap.exe

wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/56.0.2/win64/en-US/Firefox%20Setup%2056.0.2.exe -O firefox.exe

wget https://1.na.dl.wireshark.org/win64/Wireshark-win64-2.4.2.exe -O wireshark.exe

wget https://www.mls-software.com/files/setupssh-7.6p1-1.exe -O setupssh.exe

wget https://github.com/Microsoft/WindowsProtocolTestSuites/releases/download/2.0/ProtocolTestManager.msi -O ProtocolTestManager.msi

wget https://github.com/Microsoft/WindowsProtocolTestSuites/releases/download/2.0/ADFamily-TestSuite-ServerEP.msi -O ADFamily_TestSuite-ServerEP.msi

wget https://github.com/Microsoft/WindowsProtocolTestSuites/releases/download/2.0/Kerberos-TestSuite-ServerEP.msi -O Kerberos-TestSuite-ServerEP.msi

wget https://github.com/Microsoft/WindowsProtocolTestSuites/releases/download/2.0/MS-AZOD-TestSuite-ODEP.msi -O MS-AZOD-TestSuite-ODEP.msi
