#!/bin/sh

tag="$1"
if [ "$2" != "" ]; then
    start="$2"
else
    start=origin/master
fi

cd "$(git rev-parse --show-toplevel)"

git filter-branch  -f \
    --msg-filter "$(dirname $0)/git_review.msg-filter.awk -v tag='${tag}'" \
    "$start"..
