#!/bin/bash

machine=$1

KNOWN_HOSTS=~/.known-hosts-on-catalyst-cloud/$machine
CLOUD_DOT_FILES=~/cloud-dot-files

echo checking whether $machine has a floating IP...

ip=$(nova list | grep "| $machine " | cut -d'|' -f7 | cut -d, -f2 -s | tr -d '[:space:]')

if [[ "$ip" ]]; then
    echo found IP $ip
else
    for x in 1 2; do
        echo looking for a free IP
        ip=$(openstack  floating ip list | cut -d'|' -f 3,4 -s | grep -e '| None' | head -1 | cut -d'|' -f1)
        if [[ "$ip" ]]; then
            echo using $ip
            break
        else
            echo no free floating IPs; creating a new one...
            openstack floating ip create
        fi
    done

    nova floating-ip-associate $machine $ip
    rm -f $KNOW_HOSTS
fi

# make sure $ip has no trailing space (or else rsync $ip: will fail)
ip=${ip// }

# copy the dot files if this looks like the first connection

if [[ -d $CLOUD_DOT_FILES && ! -f $KNOWN_HOSTS ]]; then
    mkdir -p $(dirname $KNOWN_HOSTS)
    echo "copying $CLOUD_DOT_FILES/ contents to remote $ip:"
    rsync -v -e "ssh -o 'UserKnownHostsFile $KNOWN_HOSTS' -o 'User ubuntu'" -r "$CLOUD_DOT_FILES/" "$ip":
fi

ssh -o "UserKnownHostsFile $KNOWN_HOSTS" -o 'User ubuntu' $ip



# for windows machines:
#xfreerdp -v $ip -u 'SAMDOM\Administrator' -clipboard
