---
# vars need override while use role
ENV_NAME: test

OS_NETWORK_NAME: "{{ ENV_NAME }}-network"
OS_ROUTER_NAME: "{{ ENV_NAME }}-router"
OS_SUBNET_NAME: "{{ ENV_NAME }}-subnet"
OS_SUBNET_CIDR: "10.0.0.0/24"

samba_user: Administrator
samba_password: Password01@

## Porirua region DNS
OS_NAMESERVERS: [202.78.247.197, 202.78.247.198, 202.78.247.199]

OS_IMAGE_NAME: ubuntu-16.04-x86_64
OS_FLAVOR_NAME: c1.c1r1
OS_USERDATA_FILE: "{{role_path}}/templates/userdata.sh"
OS_AUTO_FLOATING_IP: yes

package_list_file: "{{role_path}}/../../package-lists/ubuntu"

OS_META_GROUPS: ['openstack']
# used when you create servers in batch
OS_SERVER_PREFIX: 'server'

OS_KEYPAIR_NAME: catalyst_samba
OS_PUBLIC_KEY_FILE: "{{ role_path }}/files/id_rsa_catalyst_samba.pub"

OS_SECURITY_GROUP: domain

OS_SECURITY_GROUPS:
  - "{{OS_SECURITY_GROUP}}"

security_groups:
  domain:
    - protocol: tcp  # tcp traffic in domain
      remote_group: domain
    - protocol: udp  # tcp traffic in domain
      remote_group: domain
    - protocol: icmp  # ping
      remote_ip_prefix: 202.78.240.7/32
    - protocol: tcp  # ssh
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 202.78.240.7/32
    - protocol: tcp  # winrm
      port_range_min: 5985
      port_range_max: 5986
      remote_ip_prefix: 202.78.240.7/32
    - protocol: tcp  # rdp
      port_range_min: 3389
      port_range_max: 3389
      remote_ip_prefix: 202.78.240.7/32

ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/env python3

# present or absent
state: present
# when state is absent, do we delete network, subnet, and router
# currently os_router is broken, so we will set this to no for now
delete_network: no

# run packer build to build image
run_packer_build: no
# use the packer image, you can skip packer build, use a existing image
# to not use packer image, set this to empty
PACKER_OUTPUT_IMAGE_NAME: "packer-{{OS_IMAGE_NAME}}"
