---
# vars need override while use role
ENV_NAME: test

OS_NETWORK_NAME: "{{ ENV_NAME }}-network"
OS_ROUTER_NAME: "{{ ENV_NAME }}-router"
OS_SUBNET_NAME: "{{ ENV_NAME }}-subnet"
OS_SUBNET_CIDR: "10.0.0.0/24"

## Porirua region DNS
OS_NAMESERVERS: [202.78.247.197, 202.78.247.198, 202.78.247.199]

OS_IMAGE_NAME: ubuntu-16.04-x86_64
OS_FLAVOR_NAME: c1.c1r1

OS_AUTO_FLOATING_IP: yes

OS_SECURITY_GROUPS:
  - default
  - ad-domain-and-clients

OS_META_GROUPS: ['openstack']
# used when you create servers in batch
OS_SERVER_PREFIX: 'server'

OS_KEYPAIR_NAME: catalyst_samba
OS_PUBLIC_KEY_FILE: "{{ role_path }}/files/id_rsa_catalyst_samba.pub"

security_groups:
  ssh:
    - protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 202.78.240.7/32
  ping:
    - protocol: icmp
      remote_ip_prefix: 202.78.240.7/32
  domain:
    - protocol: tcp
      remote_group: domain
    - protocol: udp
      remote_group: domain
    - protocol: icmp
      remote_group: domain
  winrm:
    - protocol: tcp
      port_range_min: 5985
      port_range_max: 5986
      remote_ip_prefix: 202.78.240.7/32
  rdp:
    - protocol: tcp
      port_range_min: 3389
      port_range_max: 3389
      remote_ip_prefix: 202.78.240.7/32

ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/env python3

# present or absent
state: present
