---

- name: Pre-run checks
  hosts: localhost
  tasks:
    - name: Fail if env_prefix variable is set
      local_action: fail msg="env_prefix is not defined, run ansible with -e env_prefix=<your_unique_env_prefix> option (unquoted)"
      when: ( env_prefix is not defined ) or ( env_prefix is none ) or ( env_prefix | trim == '' )
      tags:
        - always

    - name: Check who am I
      command: whoami
      register: whoami
      when: ( keypair_name is not defined ) or ( keypair_name is none ) or ( keypair_name | trim == '' )
      changed_when: false
      tags:
        - always

    - name: Set keypair_name to be current username by default
      set_fact:
        keypair_name: "{{ whoami.stdout_lines[0] }}"
      when: ( whoami is defined ) and ( whoami.stdout_lines is defined ) and ( whoami.stdout_lines[0] is defined )
      tags:
        - always

    - name: Fail if keypair_name variable is set
      local_action: fail msg="keypair_name is not defined, define it in group_vars/all or as ansible '-e' option parameter"
      when: ( keypair_name is not defined ) or ( keypair_name is none ) or ( keypair_name | trim == '' )
      tags:
        - always
