heat_template_version: 2014-10-16

description: >
  A template to create multiple Samba DCs across many networks.

parameters:
  servers_per_subnet:
    default: 2
    type: number
    description: How many servers to build in each subnet

  subnet_count:
    default: 2
    type: number
    description: How many subnets to build

  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair

  user:
    type: string
    description: Admin user
    default: "ubuntu"
    constraints:
      - allowed_pattern: "[a-z_][a-z0-9_]{0,30}"
        description: Lowercase please, no fancy characters, not too long.

  tmpfs:
    type: string
    description: tmpfs flag
    default: "False"
    constraints:
      - allowed_pattern: "True|False"
        description: True to use tmpfs, False for real disk

  flavor:
    type: string
    description: Flavor for the server to be created
    default: c1.c2r4
    constraints:
      - custom_constraint: nova.flavor

  image:
    type: string
    default: ubuntu-15.04
    description: Image ID or image name to use for the server
    constraints:
      - custom_constraint: glance.image

  remote:
    default: git://git.catalyst.net.nz/samba.git
    type: string
    description: URL of git remote

  branch:
    type: string
    description: git branch to use

  samba_realm:
    type: string
    default: "SAMDOM.EXAMPLE.COM"
    description: Realm for the samba DCs

  samba_domain:
    type: string
    default: "SAMDOM"
    description: Domain for the samba DCs

  samba_password:
    type: string
    default: "penguin12#"
    description: Password for the samba DCs

  package_list:
    type: comma_delimited_list
    description: package to install

  public_net:
    type: string
    default: public-net
    description: >
      ID or name of the public network

  use_samba_kcc:
    type: boolean
    default: true
    description: Use the new samba_kcc

  kcc_interval:
    type: number
    default: 0
    description: interval between KCC  runs (seconds)


resources:
  subnets:
    type: OS::Heat::ResourceGroup
    depends_on: router
    properties:
      count: {get_param: subnet_count}
      resource_def:
        type: single-site.yaml
        properties:
          name:
            str_replace:
              template:
                subnet-X
              params:
                X: "%index%"
          subnet_id:
            str_replace:
              template:
                X
              params:
                X: "%index%"
          subnet_count: { get_param: subnet_count }
          server_count: { get_param: servers_per_subnet }
          key_name: { get_param: key_name }
          user: { get_param: user }
          tmpfs: { get_param: tmpfs }
          flavor: { get_param: flavor }
          image: { get_param: image }
          remote: { get_param: remote }
          branch: { get_param: branch }
          samba_realm: { get_param: samba_realm }
          samba_domain: { get_param: samba_domain }
          samba_password: { get_param: samba_password }
          package_list: { get_param: package_list }
          stack_name: { get_param: "OS::stack_name" }
          use_samba_kcc: { get_param: use_samba_kcc }
          kcc_interval: { get_param: kcc_interval }

          router: {get_resource: router }
          private_net_cidr:
            str_replace:
              template:
                10.9.X.0/24
              params:
                X: "%index%"
          nameservers: [10.9.0.10, 202.78.247.198]
          #nameservers: [127.0.0.1, 10.9.0.10, 202.78.247.198]

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }
