heat_template_version: 2014-10-16

description: >
  A template to create multiple Samba DCs across many networks.

parameters:
  count:
    type: number
  image:
    type: string
  flavor:
    type: string
    
  private_net_name:
    type: string
    default: private-keep-out
    description: Name of private network to be created

  public_net:
    type: string
    default: public-net
    description: >
      ID or name of the public network

  private_net_name:
    type: string
    default: private-keep-out
    description: Name of private network to be created

  private_net_cidr:
    default: 10.9.8.0/24
    type: string
    description: Private network address (CIDR notation)

  private_net_gateway:
    default: 10.9.8.1
    type: string
    description: Private network gateway address


    
resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      gateway_ip: { get_param: private_net_gateway }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

      
  servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: count }
      resource_def:
        type: OS::Nova::Server
        properties:
          name: server-%index%
          image: { get_param: image }
          flavor: { get_param: flavor }
          networks:
            - network: { get_resource: private_net }

